#!/bin/bash
set -e

ACTION="${1:-install}"
SETTINGS="$HOME/.claude/settings.json"
HOOK_COMMAND="TS=\$(date '+%Y-%m-%d_%H-%M-%S'); PROJECT=\$(basename \"\$PWD\"); DIR=\"\$PWD/.vibe-logs\"; [ -f \"\$DIR/.disabled\" ] && exit 0; mkdir -p \"\$DIR\"; [ ! -f \"\$DIR/README.md\" ] && printf '# .vibe-logs\n\nAuto-generated by [VibeLogger](https://github.com/kevinstackio/vibe-logger).\n\n## Commands\n\n- \`log session\` — manually log the current session\n- \`disable vibe logger\` — stop auto-logging for this project\n- \`enable vibe logger\` — resume auto-logging for this project\n' > \"\$DIR/README.md\"; BRANCH=\$(git branch --show-current 2>/dev/null || echo N/A); COMMITS=\$(git log --oneline -10 2>/dev/null | sed 's/^/- /' || echo '- No commits'); DIFF=\$(git diff --stat HEAD 2>/dev/null || echo 'No changes tracked'); printf '## %s\n\n**Project:** %s\n**Branch:** \`%s\`\n**Tool:** Claude Code\n**Summary:** *(auto-logged on session stop)*\n\n### Commits\n%s\n\n### Files touched\n%s\n' \"\$TS\" \"\$PROJECT\" \"\$BRANCH\" \"\$COMMITS\" \"\$DIFF\" > \"\$DIR/\$TS.md\""

install_vibe_logger() {
  echo "Installing VibeLogger..."

  # Create settings file if not exists
  if [ ! -f "$SETTINGS" ]; then
    mkdir -p "$(dirname "$SETTINGS")"
    echo '{}' > "$SETTINGS"
  fi

  # Check if already installed
  if grep -q "vibe-logger" "$SETTINGS" 2>/dev/null; then
    echo "VibeLogger is already installed."
    exit 0
  fi

  # Merge hook into settings.json using python3
  python3 - <<PYEOF
import json, sys

with open('$SETTINGS', 'r') as f:
    settings = json.load(f)

hook_entry = {
    "hooks": [
        {
            "type": "command",
            "command": "$HOOK_COMMAND"
        }
    ]
}

if 'hooks' not in settings:
    settings['hooks'] = {}
if 'Stop' not in settings['hooks']:
    settings['hooks']['Stop'] = []

settings['hooks']['Stop'].append(hook_entry)

with open('$SETTINGS', 'w') as f:
    json.dump(settings, f, indent=2)
    f.write('\n')

print("VibeLogger installed ✓")
PYEOF
}

uninstall_vibe_logger() {
  echo "Uninstalling VibeLogger..."

  if [ ! -f "$SETTINGS" ]; then
    echo "Nothing to uninstall."
    exit 0
  fi

  python3 - <<PYEOF
import json

with open('$SETTINGS', 'r') as f:
    settings = json.load(f)

if 'hooks' in settings and 'Stop' in settings['hooks']:
    settings['hooks']['Stop'] = [
        h for h in settings['hooks']['Stop']
        if 'vibe-logger' not in str(h) and 'vibe_logs' not in str(h)
    ]
    if not settings['hooks']['Stop']:
        del settings['hooks']['Stop']
    if not settings['hooks']:
        del settings['hooks']

with open('$SETTINGS', 'w') as f:
    json.dump(settings, f, indent=2)
    f.write('\n')

print("VibeLogger uninstalled ✓")
PYEOF
}

case "$ACTION" in
  install)   install_vibe_logger ;;
  uninstall) uninstall_vibe_logger ;;
  *)
    echo "Usage: curl ... | bash -s [install|uninstall]"
    exit 1
    ;;
esac
